export const documentTypes = [
  {
    label: 'All',
    count: 58,
    size: '53.94 MB',
    icon: 'file-document-outline',
    color: '#4A90E2',
  },
  {
    label: 'DOC',
    count: 2,
    size: '824.39 KB',
    icon: 'file-word-outline',
    color: '#3b82f6',
  },
  {
    label: 'PDF',
    count: 52,
    size: '52.57 MB',
    icon: 'file-pdf-box',
    color: '#ef4444',
  },
  {
    label: 'XLS',
    count: 1,
    size: '30.22 KB',
    icon: 'file-excel-box',
    color: '#10b981',
  },
  {
    label: 'PPT',
    count: 0,
    size: '0 Bytes',
    icon: 'file-powerpoint-box',
    color: '#f97316',
  },
  {
    label: 'CSV',
    count: 0,
    size: '0 Bytes',
    icon: 'file-delimited-outline',
    color: '#ec4899',
  },
  {
    label: 'TXT',
    count: 0,
    size: '0 Bytes',
    icon: 'file-document-edit-outline',
    color: '#eab308',
  },
  {
    label: 'RTF',
    count: 0,
    size: '0 Bytes',
    icon: 'file-rotate-right',
    color: '#8b5cf6',
  },
  {
    label: 'XML',
    count: 0,
    size: '0 Bytes',
    icon: 'file-code-outline',
    color: '#06b6d4',
  },
  {
    label: 'Other',
    count: 0,
    size: '',
    icon: 'file-question-outline',
    color: '#6b7280',
  },
];
